Added also evaluating on note level (as well as int level)

diff --git a/eval_run b/eval_run
--- a/eval_run
+++ b/eval_run
@@ -1,7 +1,27 @@
 #!/bin/bash
-DEBUG=FALSE
+DEBUG="FALSE"
+PORT="5678"
+while (( "$#" )); do
+  case "$1" in
+    --debug)
+      DEBUG="TRUE"
+      shift
+      ;;
+    --port)
+      PORT="$2"
+      shift 2
+      ;;
+    --)
+      shift
+      break
+      ;;
+    *)
+      echo "Error: Invalid argument"
+      exit 1
+  esac
+done
 if [ "$DEBUG" = "TRUE" ]; then
-    CMD="python -m debugpy --listen 127.0.0.1:5678 --wait-for-client"
+    CMD="python -m debugpy --listen 127.0.0.1:${PORT} --wait-for-client"
 else
     CMD="python"
 fi
